name: CI Artifact Check

on:
  push:
    branches: [ "main", "feature/*", "features/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t shipit .

      - name: Run Test Container
        run: docker run --rm shipit